
x-backend-test: &backend-test
  build:
    context: .
    dockerfile: Dockerfile
    target: test
  volumes:
    - ./app:/src/app:z
    - ./tests:/src/tests:z    
    - ./migrations:/src/migrations:z
    - ./alembic.ini:/src/alembic.ini:z
    - ./pyproject.toml:/src/pyproject.toml
  
services:
  pytest:
    <<: *backend-test
    command: ["pytest", "-v"]
    env_file:
      ./tests/.env.pytest
    depends_on:
      db_test:
        condition: service_healthy
      migrator_test:
        condition: service_completed_successfully
      seeder_test:
        condition: service_completed_successfully
    networks:
      - test_network

  db_test:
    image: postgres:17.4-alpine3.21
    restart: "no"
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: test_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER -d $PG_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test_network


  migrator_test:
    <<: *backend-test
    command: ["alembic", "upgrade", "head"]
    env_file:
      ./tests/.env.pytest
    depends_on:
      db_test:
        condition: service_healthy
    networks:
      - test_network
  
  seeder_test:
    <<: *backend-test
    command: ["python", "-m", "app.seed.data"]

    # This service should not restart after it has successfully completed its job
    restart: "no"
    env_file:
      - ./tests/.env.pytest
    depends_on:
      - migrator_test
      - db_test
    networks:
      - test_network


networks:
  test_network:
    driver: bridge