"""change_uq_activity_task

Revision ID: 096a9ef46a20
Revises: b807c46724da
Create Date: 2026-01-08 11:26:09.083730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096a9ef46a20'
down_revision: Union[str, Sequence[str], None] = 'b807c46724da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_activity_task_title'), 'activity_tasks', type_='unique')
    op.create_unique_constraint('uq_activity_id_user_id', 'activity_tasks', ['activity_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_activity_id_user_id', 'activity_tasks', type_='unique')
    op.create_unique_constraint(op.f('uq_activity_task_title'), 'activity_tasks', ['activity_id', 'title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
