"""removed_unexpected_hours_monthly_field

Revision ID: 13d08d795146
Revises: c1c963e4f75d
Create Date: 2026-01-28 10:31:33.147706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d08d795146'
down_revision: Union[str, Sequence[str], None] = 'c1c963e4f75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'expected_hours_monthly')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('expected_hours_monthly', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
