"""added_reltaions_to_user_tasks_worklogs

Revision ID: 21ce19e90146
Revises: c2d9b55b6856
Create Date: 2026-01-08 09:01:31.105213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ce19e90146'
down_revision: Union[str, Sequence[str], None] = 'c2d9b55b6856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_tasks', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_activity_task_title', 'activity_tasks', ['activity_id', 'title'])
    op.create_foreign_key(None, 'activity_tasks', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('worklogs', 'duration',
               existing_type=sa.SMALLINT(),
               type_=sa.Numeric(precision=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worklogs', 'duration',
               existing_type=sa.Numeric(precision=1),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'activity_tasks', type_='foreignkey')
    op.drop_constraint('uq_activity_task_title', 'activity_tasks', type_='unique')
    op.drop_column('activity_tasks', 'user_id')
    # ### end Alembic commands ###
