"""activity_user_optional_values

Revision ID: 49987cbed3c3
Revises: b707471af2d6
Create Date: 2026-01-28 09:52:08.907408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49987cbed3c3'
down_revision: Union[str, Sequence[str], None] = 'b707471af2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_tasks', 'activity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('activity_tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('activity_tasks_activity_id_fkey'), 'activity_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'activity_tasks', 'activities', ['activity_id'], ['id'], ondelete='SET NULL')
    op.alter_column('activity_users', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('activity_users', 'activity_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_users', 'activity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activity_users', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'activity_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('activity_tasks_activity_id_fkey'), 'activity_tasks', 'activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.alter_column('activity_tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activity_tasks', 'activity_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
