"""task_worklog_delete_on_task_delete

Revision ID: 67db1745f3a7
Revises: 83ceff1ec61d
Create Date: 2026-03-10 20:06:49.271331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67db1745f3a7'
down_revision: Union[str, Sequence[str], None] = '83ceff1ec61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worklogs', 'activity_task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('worklogs_activity_task_id_fkey'), 'worklogs', type_='foreignkey')
    op.create_foreign_key(None, 'worklogs', 'activity_tasks', ['activity_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worklogs', type_='foreignkey')
    op.create_foreign_key(op.f('worklogs_activity_task_id_fkey'), 'worklogs', 'activity_tasks', ['activity_task_id'], ['id'], ondelete='SET NULL')
    op.alter_column('worklogs', 'activity_task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
