"""uq_activity_task_fields

Revision ID: 680916d7f93f
Revises: 7a4e82da4bf5
Create Date: 2026-04-02 06:31:58.832315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680916d7f93f'
down_revision: Union[str, Sequence[str], None] = '7a4e82da4bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_title_activity_id'), 'activity_tasks', type_='unique')
    op.create_unique_constraint('uq_title_activity_id_user_id', 'activity_tasks', ['title', 'activity_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_title_activity_id_user_id', 'activity_tasks', type_='unique')
    op.create_unique_constraint(op.f('uq_title_activity_id'), 'activity_tasks', ['title', 'activity_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
