"""activity_task_uq_constraint

Revision ID: 77d81d86ad07
Revises: 13d08d795146
Create Date: 2026-02-27 12:42:47.644625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d81d86ad07'
down_revision: Union[str, Sequence[str], None] = '13d08d795146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_title_user_id'), 'activity_tasks', type_='unique')
    op.create_unique_constraint('uq_title_activity_id', 'activity_tasks', ['title', 'activity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_title_activity_id', 'activity_tasks', type_='unique')
    op.create_unique_constraint(op.f('uq_title_user_id'), 'activity_tasks', ['title', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
