"""task_period_uniquness

Revision ID: 83ceff1ec61d
Revises: 967828c46e3f
Create Date: 2026-03-10 18:35:54.003219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ceff1ec61d'
down_revision: Union[str, Sequence[str], None] = '967828c46e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_tasks', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('activity_tasks', sa.Column('year', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_title_activity_id'), 'activity_tasks', type_='unique')
    op.create_unique_constraint('uq_title_activity_id_month_year', 'activity_tasks', ['title', 'activity_id', 'month', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_title_activity_id_month_year', 'activity_tasks', type_='unique')
    op.create_unique_constraint(op.f('uq_title_activity_id'), 'activity_tasks', ['title', 'activity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('activity_tasks', 'year')
    op.drop_column('activity_tasks', 'month')
    # ### end Alembic commands ###
