"""worklog_task_id_nullable

Revision ID: 967828c46e3f
Revises: 77d81d86ad07
Create Date: 2026-03-03 20:24:28.565629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967828c46e3f'
down_revision: Union[str, Sequence[str], None] = '77d81d86ad07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worklogs', 'activity_task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worklogs', 'activity_task_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
