"""fix_activity_uq_constraint

Revision ID: b807c46724da
Revises: 21ce19e90146
Create Date: 2026-01-08 09:09:58.873584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b807c46724da'
down_revision: Union[str, Sequence[str], None] = '21ce19e90146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_tasks_title_key'), 'activity_tasks', type_='unique')
    op.alter_column('worklogs', 'duration',
               existing_type=sa.NUMERIC(precision=1, scale=0),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worklogs', 'duration',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.NUMERIC(precision=1, scale=0),
               existing_nullable=False)
    op.create_unique_constraint(op.f('activity_tasks_title_key'), 'activity_tasks', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
