"""add_reporting_period_table

Revision ID: b8f7db445cff
Revises: 967828c46e3f
Create Date: 2026-03-07 12:22:52.459528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f7db445cff'
down_revision: Union[str, Sequence[str], None] = '967828c46e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity_tasks', sa.Column('period_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_title_activity_id'), 'activity_tasks', type_='unique')
    op.create_unique_constraint('uq_title_activity_id_period_id', 'activity_tasks', ['title', 'activity_id', 'period_id'])
    op.create_foreign_key(None, 'activity_tasks', 'reporting_periods', ['period_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_tasks', type_='foreignkey')
    op.drop_constraint('uq_title_activity_id_period_id', 'activity_tasks', type_='unique')
    op.create_unique_constraint(op.f('uq_title_activity_id'), 'activity_tasks', ['title', 'activity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('activity_tasks', 'period_id')
    op.drop_table('reporting_periods')
    # ### end Alembic commands ###
