"""tenant_based_design

Revision ID: bc85590990c4
Revises: 680916d7f93f
Create Date: 2026-04-11 10:53:47.410149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc85590990c4'
down_revision: Union[str, Sequence[str], None] = '680916d7f93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activities', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index('ix_activity_tenant_id', 'activities', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_activity_code_tenant', 'activities', ['code', 'tenant_id'])
    op.create_foreign_key(None, 'activities', 'tenants', ['tenant_id'], ['id'])
    op.add_column('activity_tasks', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index('ix_task_tenant_user', 'activity_tasks', ['tenant_id', 'user_id'], unique=False)
    op.create_foreign_key(None, 'activity_tasks', 'tenants', ['tenant_id'], ['id'])
    op.add_column('activity_users', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.alter_column('activity_users', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activity_users', 'activity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activity_users', 'assigned_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('uq_user_activity'), 'activity_users', type_='unique')
    op.create_unique_constraint('uq_tenant_user_activity', 'activity_users', ['tenant_id', 'user_id', 'activity_id'])
    op.drop_constraint(op.f('activity_users_assigned_by_id_fkey'), 'activity_users', type_='foreignkey')
    op.drop_constraint(op.f('activity_users_user_id_fkey'), 'activity_users', type_='foreignkey')
    op.drop_constraint(op.f('activity_users_activity_id_fkey'), 'activity_users', type_='foreignkey')
    op.create_foreign_key(None, 'activity_users', 'activities', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'activity_users', 'users', ['assigned_by_id'], ['id'])
    op.create_foreign_key(None, 'activity_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'activity_users', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    op.add_column('worklogs', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index('ix_worklog_tenant_date', 'worklogs', ['tenant_id', 'date'], unique=False)
    op.create_index('ix_worklog_tenant_user_data', 'worklogs', ['tenant_id', 'user_id', 'date'], unique=False)
    op.create_foreign_key(None, 'worklogs', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worklogs', type_='foreignkey')
    op.drop_index('ix_worklog_tenant_user_data', table_name='worklogs')
    op.drop_index('ix_worklog_tenant_date', table_name='worklogs')
    op.drop_column('worklogs', 'tenant_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'activity_users', type_='foreignkey')
    op.drop_constraint(None, 'activity_users', type_='foreignkey')
    op.drop_constraint(None, 'activity_users', type_='foreignkey')
    op.drop_constraint(None, 'activity_users', type_='foreignkey')
    op.create_foreign_key(op.f('activity_users_activity_id_fkey'), 'activity_users', 'activities', ['activity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('activity_users_user_id_fkey'), 'activity_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('activity_users_assigned_by_id_fkey'), 'activity_users', 'users', ['assigned_by_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_tenant_user_activity', 'activity_users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_activity'), 'activity_users', ['user_id', 'activity_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('activity_users', 'assigned_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('activity_users', 'activity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('activity_users', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('activity_users', 'tenant_id')
    op.drop_constraint(None, 'activity_tasks', type_='foreignkey')
    op.drop_index('ix_task_tenant_user', table_name='activity_tasks')
    op.drop_column('activity_tasks', 'tenant_id')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint('uq_activity_code_tenant', 'activities', type_='unique')
    op.drop_index('ix_activity_tenant_id', table_name='activities')
    op.drop_column('activities', 'tenant_id')
    op.drop_table('tenants')
    # ### end Alembic commands ###
