"""change_unique_constraint_activity_tasks

Revision ID: c1c963e4f75d
Revises: 49987cbed3c3
Create Date: 2026-01-28 10:12:03.098069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c963e4f75d'
down_revision: Union[str, Sequence[str], None] = '49987cbed3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_activity_id_user_id'), 'activity_tasks', type_='unique')
    op.create_unique_constraint('uq_title_user_id', 'activity_tasks', ['title', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_title_user_id', 'activity_tasks', type_='unique')
    op.create_unique_constraint(op.f('uq_activity_id_user_id'), 'activity_tasks', ['activity_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
