"""tenant_id_to_session

Revision ID: e4253eef7bd0
Revises: bc85590990c4
Create Date: 2026-04-11 11:27:08.854408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4253eef7bd0'
down_revision: Union[str, Sequence[str], None] = 'bc85590990c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'tenant_id')
    # ### end Alembic commands ###
