"""at_field_session

Revision ID: eecd4fb2c634
Revises: 7c0001b03f71
Create Date: 2025-12-29 13:20:07.099647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecd4fb2c634'
down_revision: Union[str, Sequence[str], None] = '7c0001b03f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('access_token_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_sessions_access_token_hash'), 'sessions', ['access_token_hash'], unique=False)
    op.add_column('todos', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_id')
    op.drop_index(op.f('ix_sessions_access_token_hash'), table_name='sessions')
    op.drop_column('sessions', 'access_token_hash')
    # ### end Alembic commands ###
